//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnersApp.dbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PartnersDBEntities : DbContext
    {
        public PartnersDBEntities()
            : base("name=PartnersDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Partners> Partners { get; set; }
        public DbSet<PartnerTypes> PartnerTypes { get; set; }
        public DbSet<Products> Products { get; set; }
        public DbSet<SalesHistory> SalesHistory { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
