//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnersApp.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        public Partners()
        {
            this.SalesHistory = new HashSet<SalesHistory>();
        }
    
        public int PartnerID { get; set; }
        public string PartnerName { get; set; }
        public int PartnerTypeID { get; set; }
        public string DirectorName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public int Rating { get; set; }
    
        public virtual PartnerTypes PartnerTypes { get; set; }
        public virtual ICollection<SalesHistory> SalesHistory { get; set; }
    }
}
