//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnersApp.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerTypes
    {
        public PartnerTypes()
        {
            this.Partners = new HashSet<Partners>();
        }
    
        public int PartnerTypeID { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<Partners> Partners { get; set; }
    }
}
