//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnersApp.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.SalesHistory = new HashSet<SalesHistory>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
    
        public virtual ICollection<SalesHistory> SalesHistory { get; set; }
    }
}
