//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnersApp.dbContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesHistory
    {
        public int SaleID { get; set; }
        public int PartnerID { get; set; }
        public int ProductID { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int Quantity { get; set; }
    
        public virtual Partners Partners { get; set; }
        public virtual Products Products { get; set; }
        public decimal TotalAmount { get; set; }
    }
}
